#!/bin/bash
# ==============================================
# B@tHome - VM Waller
# Utilisateur: monops / Hostname: waller
# IP: 10.10.20.112 / RAM: 2 Go
# Services:
#   - Grafana        (port 3000) -> grafana.waynenet.eu
#   - InfluxDB       (port 8086)
#   - Uptime Kuma    (port 3001) -> waller.waynenet.eu
#   - Termix         (port 8888) -> termix.waynenet.eu
#   - Prometheus     (port 9090) [collecte metriques Node Exporter]
#   - UniFi Log Insights (port 4000)
# LANCER EN ROOT : su - puis bash waller.sh
# ==============================================

SCRIPT_URL="https://raw.githubusercontent.com/SphinxXV/bathome-scripts/main/init/init.sh"

echo "B@tHome - Initialisation de Waller (Monitoring + Terminal)"
curl -fsSL $SCRIPT_URL -o /tmp/init.sh
bash /tmp/init.sh monops waller
rm /tmp/init.sh

echo ""
echo "============================================================"
echo "Installation des services de monitoring..."
echo "============================================================"

mkdir -p /home/monops/docker/waller
cd /home/monops/docker/waller

cat > docker-compose.yml << 'EOF'
services:

  # InfluxDB - Base de donnees time-series pour les metriques
    influxdb:
        container_name: influxdb
            image: influxdb:2.7
                restart: unless-stopped
                    ports:
                          - "8086:8086"
                              volumes:
                                    - ./influxdb-data:/var/lib/influxdb2
                                          - ./influxdb-config:/etc/influxdb2
                                              environment:
                                                    DOCKER_INFLUXDB_INIT_MODE: setup
                                                          DOCKER_INFLUXDB_INIT_USERNAME: admin
                                                                DOCKER_INFLUXDB_INIT_PASSWORD: CHANGER_CE_MOT_DE_PASSE
                                                                      DOCKER_INFLUXDB_INIT_ORG: bathome
                                                                            DOCKER_INFLUXDB_INIT_BUCKET: network

                                                                              # Prometheus - Collecte les metriques Node Exporter de toutes les VMs
                                                                                prometheus:
                                                                                    container_name: prometheus
                                                                                        image: prom/prometheus:latest
                                                                                            restart: unless-stopped
                                                                                                ports:
                                                                                                      - "9090:9090"
                                                                                                          volumes:
                                                                                                                - ./prometheus-config:/etc/prometheus
                                                                                                                      - ./prometheus-data:/prometheus
                                                                                                                          command:
                                                                                                                                - '--config.file=/etc/prometheus/prometheus.yml'
                                                                                                                                      - '--storage.tsdb.retention.time=30d'
                                                                                                                                      
                                                                                                                                        # Grafana - Dashboard de monitoring CPU/RAM/Disk/Reseau
                                                                                                                                          grafana:
                                                                                                                                              container_name: grafana
                                                                                                                                                  image: grafana/grafana:latest
                                                                                                                                                      restart: unless-stopped
                                                                                                                                                          ports:
                                                                                                                                                                - "3000:3000"
                                                                                                                                                                    volumes:
                                                                                                                                                                          - ./grafana-data:/var/lib/grafana
                                                                                                                                                                              environment:
                                                                                                                                                                                    GF_SECURITY_ADMIN_USER: admin
                                                                                                                                                                                          GF_SECURITY_ADMIN_PASSWORD: CHANGER_CE_MOT_DE_PASSE
                                                                                                                                                                                                GF_SERVER_ROOT_URL: https://grafana.waynenet.eu
                                                                                                                                                                                                    depends_on:
                                                                                                                                                                                                          - prometheus
                                                                                                                                                                                                                - influxdb
                                                                                                                                                                                                                
                                                                                                                                                                                                                  # Uptime Kuma - Surveillance disponibilite de tous les services
                                                                                                                                                                                                                    uptime-kuma:
                                                                                                                                                                                                                        container_name: uptime-kuma
                                                                                                                                                                                                                            image: louislam/uptime-kuma:latest
                                                                                                                                                                                                                                restart: unless-stopped
                                                                                                                                                                                                                                    ports:
                                                                                                                                                                                                                                          - "3001:3001"
                                                                                                                                                                                                                                              volumes:
                                                                                                                                                                                                                                                    - ./uptime-kuma-data:/app/data
                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                      # Termix - Terminal SSH web (acces a toutes les VMs depuis navigateur)
                                                                                                                                                                                                                                                        # Acces: https://termix.waynenet.eu
                                                                                                                                                                                                                                                          termix:
                                                                                                                                                                                                                                                              container_name: termix
                                                                                                                                                                                                                                                                  image: ghcr.io/nicholaswilde/termix:latest
                                                                                                                                                                                                                                                                      restart: unless-stopped
                                                                                                                                                                                                                                                                          ports:
                                                                                                                                                                                                                                                                                - "8888:3000"
                                                                                                                                                                                                                                                                                    volumes:
                                                                                                                                                                                                                                                                                          - ./termix-data:/root/.config/termix
                                                                                                                                                                                                                                                                                              environment:
                                                                                                                                                                                                                                                                                                    - TZ=Europe/Paris
                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                      # UniFi Log Insights
                                                                                                                                                                                                                                                                                                        unifi-log-insights:
                                                                                                                                                                                                                                                                                                            container_name: unifi-log-insights
                                                                                                                                                                                                                                                                                                                image: ghcr.io/jmasarweh/unifi-log-insights:latest
                                                                                                                                                                                                                                                                                                                    restart: unless-stopped
                                                                                                                                                                                                                                                                                                                        ports:
                                                                                                                                                                                                                                                                                                                              - "4000:4000"
                                                                                                                                                                                                                                                                                                                                    - "5514:5514/udp"
                                                                                                                                                                                                                                                                                                                                          - "8765:8765"
                                                                                                                                                                                                                                                                                                                                              volumes:
                                                                                                                                                                                                                                                                                                                                                    - ./uli-data:/app/data
                                                                                                                                                                                                                                                                                                                                                        environment:
                                                                                                                                                                                                                                                                                                                                                              TZ: "Europe/Paris"
                                                                                                                                                                                                                                                                                                                                                                    UNIFI_HOST: "10.10.10.100"
                                                                                                                                                                                                                                                                                                                                                                          UNIFI_API_KEY: "METTRE_TA_CLE_API_UNIFI"
                                                                                                                                                                                                                                                                                                                                                                          EOF
                                                                                                                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                                                                                                          # Creer la configuration Prometheus
                                                                                                                                                                                                                                                                                                                                                                          mkdir -p ./prometheus-config
                                                                                                                                                                                                                                                                                                                                                                          cat > ./prometheus-config/prometheus.yml << 'PROMEOF'
                                                                                                                                                                                                                                                                                                                                                                          global:
                                                                                                                                                                                                                                                                                                                                                                            scrape_interval: 15s
                                                                                                                                                                                                                                                                                                                                                                              evaluation_interval: 15s
                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                              scrape_configs:
                                                                                                                                                                                                                                                                                                                                                                                - job_name: 'node_exporter'
                                                                                                                                                                                                                                                                                                                                                                                    static_configs:
                                                                                                                                                                                                                                                                                                                                                                                          - targets:
                                                                                                                                                                                                                                                                                                                                                                                                    - '10.10.20.111:9100'  # Cipher
                                                                                                                                                                                                                                                                                                                                                                                                              - '10.10.20.113:9100'  # Slade
                                                                                                                                                                                                                                                                                                                                                                                                                        - '10.10.20.110:9100'  # Ras
                                                                                                                                                                                                                                                                                                                                                                                                                                  - '10.10.20.117:9100'  # Floyd
                                                                                                                                                                                                                                                                                                                                                                                                                                            - '10.10.20.114:9100'  # Matches
                                                                                                                                                                                                                                                                                                                                                                                                                                                      - '10.10.20.112:9100'  # Waller (lui-meme)
                                                                                                                                                                                                                                                                                                                                                                                                                                                      PROMEOF
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      # Ports UFW
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 3000/tcp   # Grafana
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 3001/tcp   # Uptime Kuma
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 8086/tcp   # InfluxDB
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 8888/tcp   # Termix
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 9090/tcp   # Prometheus
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 4000/tcp   # UniFi Log Insights
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 5514/udp   # Syslog
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw allow 8765/tcp   # MCP
                                                                                                                                                                                                                                                                                                                                                                                                                                                      ufw reload
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      docker compose up -d
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "============================================================"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Waller installe avec succes !"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Grafana      : http://$(hostname -I | awk '{print $1}'):3000"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Uptime Kuma  : http://$(hostname -I | awk '{print $1}'):3001"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " InfluxDB     : http://$(hostname -I | awk '{print $1}'):8086"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Termix       : http://$(hostname -I | awk '{print $1}'):8888"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Prometheus   : http://$(hostname -I | awk '{print $1}'):9090"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo ""
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo " Prochaines etapes :"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "   1. Configurer DNS grafana.waynenet.eu + termix.waynenet.eu"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "   2. Ajouter proxies NPM pour Grafana + Termix"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "   3. Installer Node Exporter sur les VMs existantes"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "   4. Importer dashboard Grafana ID: 1860 (Node Exporter Full)"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      echo "============================================================"
                                                                                                                                                                                                                                                                                                                                                                                                                                                      
